lint: Add missing error handling
pkg/vf/virtio.go:178:22: Error return value of `unix.IoctlSetTermios` is not checked (errcheck)
	unix.IoctlSetTermios(int(f.Fd()), unix.TIOCSETA, attr)
	                    ^